### ISSUE TITLE
Some permissions cause the app to crash

### ISSUE THREAD

**Issue by tallnato** [Karumi/Dexter#100]
I've been trying to integrate your lib with an app that I'm doing, but i've come across with a problem,
if I request the permissions **READ_PHONE_STATE** or **READ_SMS**, my app crashes.

I've downloaded your master branch and then changed your sample to request to ask for those permissions and the same happened. 
The only change was this:
```java
@OnClick(R.id.all_permissions_button) public void onAllPermissionsButtonClicked() {
    if (Dexter.isRequestOngoing()) {
      return;
    }
    Dexter.checkPermissions(allPermissionsListener, Manifest.permission.READ_PHONE_STATE, Manifest.permission.READ_SMS);
  }
```

The crash report 
```
 FATAL EXCEPTION: main
    Process: com.karumi.dexter.sample, PID: 3668
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.karumi.dexter.sample/com.karumi.dexter.DexterActivity}: java.lang.RuntimeException: No feedback view for this permission
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
        at android.app.ActivityThread.-wrap16(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.RuntimeException: No feedback view for this permission
        at com.karumi.dexter.sample.SampleActivity.getFeedbackViewForPermission(SampleActivity.java:197)
        at com.karumi.dexter.sample.SampleActivity.showPermissionDenied(SampleActivity.java:137)
        at com.karumi.dexter.sample.SampleMultiplePermissionListener.onPermissionsChecked(SampleMultiplePermissionListener.java:41)
        at com.karumi.dexter.listener.multi.CompositeMultiplePermissionsListener.onPermissionsChecked(CompositeMultiplePermissionsListener.java:54)
        at com.karumi.dexter.MultiplePermissionListenerThreadDecorator$1.run(MultiplePermissionListenerThreadDecorator.java:45)
        at com.karumi.dexter.MainThread.execute(MainThread.java:32)
        at com.karumi.dexter.MultiplePermissionListenerThreadDecorator.onPermissionsChecked(MultiplePermissionListenerThreadDecorator.java:43)
        at com.karumi.dexter.DexterInstance.onPermissionsChecked(DexterInstance.java:278)
        at com.karumi.dexter.DexterInstance.updatePermissionsAsDenied(DexterInstance.java:261)
        at com.karumi.dexter.DexterInstance.onPermissionRequestDenied(DexterInstance.java:148)
        at com.karumi.dexter.Dexter.onPermissionsRequested(Dexter.java:176)
        at com.karumi.dexter.DexterActivity.onRequestPermissionsResult(DexterActivity.java:54)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6553)
        at android.app.Activity.dispatchActivityResult(Activity.java:6432)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742) 
        at android.app.ActivityThread.-wrap16(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```
 
Have you ever come across with this error?
Anything you can do about it?

Thanks

**Comment by Serchinastico** [comment]
Hi @tallnato,

This is actually an exception from the Sample project itself. If you want to try with other permissions there, you will need to update a couple appearances of the new permission you are using. More specifically, that exception is raised in the `getFeedbackViewForPermission` method in `SampleActivity`. Update that method so that it can find the feedback view you want to update when requesting that permission and... voilà!.

Hope that makes sense.
Thanks for reporting!
