### ISSUE TITLE
Package installer has stopped.

### ISSUE THREAD

**Issue by virtualvoid** [Karumi/Dexter#18]
This error is happenning on sample application in genymotion vm (preview of google nexus 5x, android 6) :
```java
Dexter.checkPermission(Manifest.permission.INTERNET, new EmptyPermissionListener() {
```

immediatelly FC the package manager, the logcat :
```java
11-25 12:11:01.575 3708-3708/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.android.packageinstaller, PID: 3708
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity}: java.lang.NullPointerException: Attempt to get length of null array
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                     at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.computePermissionGrantState(GrantPermissionsActivity.java:277)
                                                     at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.updateDefaultResults(GrantPermissionsActivity.java:327)
                                                     at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.onCreate(GrantPermissionsActivity.java:100)
                                                     at android.app.Activity.performCreate(Activity.java:6237)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
11-25 12:11:01.576 848-946/system_process W/ActivityManager:   Force finishing activity com.android.packageinstaller/.permission.ui.GrantPermissionsActivity
```

**Comment by pedrovgs** [comment]
Hi @virtualvoid thanks for the issue. What's the library version you are using to reproduce that bug?

**Comment by virtualvoid** [comment]
Hi @pedrovgs 

it's probably the latest : 1.0.2

I don't know if it's related, but i tried playing with <uses-permission and <uses-permission-sdk-23 and the error is gone. but dexter is now returning "granted" for every permission that i'm trying (even if it's not in manifest).

**Comment by Serchinastico** [comment]
Hi @virtualvoid 

From  the Android documentation (http://developer.android.com/training/permissions/requesting.html):

> Normal permissions do not directly risk the user's privacy. If your app lists a normal permission in its manifest, the system grants the permission automatically.

``Manifest.permission.INTERNET`` is not a dangerous permission so you shouldn't need to call Dexter to use it.  

Either way I've been doing some tests using the latest version of Dexter and looks it's doing the right thing, that is, calling the granted callback if the permission is added to the manifest and calling the denied callback when not. I'm adding the permission with a regular ``<uses-permission android:name="android.permission.INTERNET"/>`` so no modifications in that part.

**Comment by pedrovgs** [comment]
@virtualvoid can you try in a real device with a permission like the Camera or the Audio? As @Serchinastico says, you should not ask for that permission.

**Comment by virtualvoid** [comment]
Thanks for the replies. I'll look onto it.

**Comment by pedrovgs** [comment]
News about this issue @virtualvoid ?

**Comment by virtualvoid** [comment]
Unfortunately no, I haven't tested it on real device yet. But I have better
understanding of how it works beneath, so I don't think this was a real
issue anymore.

I'll check it again, when marshmallow will rollout for my LG G3.
