### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by dyxin00** [Karumi/Dexter#194]
java.lang.RuntimeException: Unable to destroy activity {com.qdu.cc/com.karumi.dexter.DexterActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.karumi.dexter.d.a()' on a null object reference
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4405)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4423)
at android.app.ActivityThread.-wrap6(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6374)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.karumi.dexter.d.a()' on a null object reference
at com.karumi.dexter.b.b(Dexter.java:145)
at com.karumi.dexter.DexterActivity.onDestroy(DexterActivity.java:37)
at android.app.Activity.performDestroy(Activity.java:6971)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1169)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4392)
... 10 more
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.karumi.dexter.d.a()' on a null object reference
at com.karumi.dexter.b.b(Dexter.java:145)
at com.karumi.dexter.DexterActivity.onDestroy(DexterActivity.java:37)
at android.app.Activity.performDestroy(Activity.java:6971)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1169)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4392)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4423)
at android.app.ActivityThread.-wrap6(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6374)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)

**Comment by pedrovgs** [comment]
Hi @dyxin00 Thanks for reporting. We have an issues template designed to help us to find the issue faster and be able to fix it asap. I'm closing this issue so you can easily rewrite it using the template 😃
