### ISSUE TITLE
DexterActivity not found in manifest

### ISSUE THREAD

**Issue by darcheville** [Karumi/Dexter#198]
Hello,

thx for your awesome library, i used it in many projects but i have a strange error today : 
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.*************/com.karumi.dexter.DexterActivity}; have you declared this activity in your AndroidManifest.xml?
11-28 09:54:06.815 3330-3330/com.************* W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1794)
11-28 09:54:06.815 3330-3330/com.************* W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
11-28 09:54:06.815 3330-3330/com.************* W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:3917)
11-28 09:54:06.816 3330-3330/com.************* W/System.err:     at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
11-28 09:54:06.816 3330-3330/com.************* W/System.err:     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
11-28 09:54:06.816 3330-3330/com.************* W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:3877)

Thx for your help,
have a great day !

**Comment by darcheville** [comment]
Works when i add : 
        <activity
            android:name="com.karumi.dexter.DexterActivity"
            android:theme="@style/Dexter.Internal.Theme.Transparent"
            />
to my manifest

**Comment by fjfdeztoro** [comment]
Thank you for reporting this issue.

Do you have any extra information? With the current report is quite hard to figure out what's going on 😅

**Comment by darcheville** [comment]
I think that could be build.gradle configuration : 

> > apply plugin: 'com.android.application'
> apply plugin: 'realm-android'
> 
> android {
>     compileSdkVersion 25
>     buildToolsVersion "25"
> 
>     defaultConfig {
>         applicationId "**********"
>         minSdkVersion 16
>         targetSdkVersion 25
>         renderscriptTargetApi 18
>         renderscriptSupportModeEnabled true
>         versionCode 29
>         versionName "2.4.0"
>         multiDexEnabled true
>     }
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
>     packagingOptions {
>         exclude 'META-INF/DEPENDENCIES.txt'
>         exclude 'META-INF/LICENSE.txt'
>         exclude 'META-INF/NOTICE.txt'
>         exclude 'META-INF/NOTICE'
>         exclude 'META-INF/LICENSE'
>         exclude 'META-INF/DEPENDENCIES'
>         exclude 'META-INF/notice.txt'
>         exclude 'META-INF/license.txt'
>         exclude 'META-INF/dependencies.txt'
>         exclude 'META-INF/LGPL2.1'
>         exclude 'META-INF/ASL2.0'
>     }
> 
>     useLibrary 'org.apache.http.legacy'
> }
> 
> dependencies {
>     compile fileTree(dir: 'libs', include: ['*.jar'])
>     testCompile 'junit:junit:4.12'
>     compile("com.mikepenz:materialdrawer:6.0.2@aar") {
>         transitive = true
>     }
>     compile 'com.github.bumptech.glide:glide:4.0.0'
>     annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'
>     compile 'com.google.android.gms:play-services-ads:+'
>     compile 'com.pixplicity.easyprefs:library:+'
>     compile group: 'org.codehaus.jackson', name: 'jackson-core-asl', version: '1.9.9'
>     compile group: 'org.codehaus.jackson', name: 'jackson-mapper-asl', version: '1.9.13'
>     compile 'com.devbrackets.android:exomedia:+'
>     compile 'com.facebook.android:facebook-android-sdk:3.23.1'
>     compile 'com.nineoldandroids:library:2.4.0+'
>     compile 'com.daimajia.easing:library:1.0.1@aar'
>     compile 'com.daimajia.androidanimations:library:1.1.3@aar'
>     compile 'org.greenrobot:eventbus:3.0.0'
>     compile 'com.karumi:dexter:+'
>     compile 'com.squareup.okhttp3:okhttp:+'
>     compile 'com.squareup.retrofit2:retrofit:2.3.0'
>     compile 'com.squareup.retrofit2:converter-gson:2.3.0'
>     compile 'com.wang.avi:library:2.1.3'
>     compile 'net.steamcrafted:materialiconlib:1.1.4'
>     compile 'com.android.support:percent:25.0.0'
>     compile 'com.android.support:design:25.1.0'
>     compile 'com.github.vajro:MaterialDesignLibrary:1.6'
>     compile 'com.jakewharton:butterknife:8.8.1'
>     annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
>     compile 'com.android.support:multidex:1.0.1'
> }
> 


Have a good day :)
