### ISSUE TITLE
No way to synchronize Dexter requests, sample app crashes

### ISSUE THREAD

**Issue by Konrad-Morawski** [Karumi/Dexter#20]
Hi there,
the library looks promising, thanks. However it's very easy to crash your sample app, all it takes is tapping on a couple of buttons rapidly (before the dialog box pops up):

    FATAL EXCEPTION: main
    Process: com.karumi.dexter.sample, PID: 2514
    java.lang.IllegalStateException: Only one Dexter request at a time is allowed
        at com.karumi.dexter.DexterInstance.checkNoDexterRequestOngoing(DexterInstance.java:215)
        at com.karumi.dexter.DexterInstance.checkPermissions(DexterInstance.java:80)
        at com.karumi.dexter.DexterInstance.checkPermission(DexterInstance.java:69)
        at com.karumi.dexter.Dexter.checkPermission(Dexter.java:57)
        at com.karumi.dexter.sample.SampleActivity.onContactsPermissionButtonClicked(SampleActivity.java:74)
        at com.karumi.dexter.sample.SampleActivity$$ViewBinder$3.doClick(SampleActivity$$ViewBinder.java:43)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:5198)
        at android.view.View$PerformClick.run(View.java:21147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

How could it be prevented? `isRequestingPermission` is private and invisible from outside, so the only way would be to create an own wrapper around Dexter and track all permission requests ourselves, but this feels cumbersome. Any ideas?

**Comment by pedrovgs** [comment]
Hi @Konrad-Morawski thanks for your issue! The developer using the library should be the one checking don't call Dexter twice without deny/accept permissions. From our side, the only thing we can do is to change the `ìsRequestingPermission`` method, but even if this method is public the developer using the library will have to check if the permission has been requested or not. What do you think @serchinastico?

**Comment by pedrovgs** [comment]
We should not throw an exception from Dexter without offer a method to check if the exception is going to be thrown or not.

**Comment by Serchinastico** [comment]
Yup, I agree with you both, we can make a public getter for that attribute to avoid forcing library clients to do exception-based flows. PRs are welcome!

**Comment by pedrovgs** [comment]
@Konrad-Morawski @flipper83 can you implement this feature?

**Comment by Konrad-Morawski** [comment]
@pedrovgs I could do this today I guess

**Comment by pedrovgs** [comment]
Cool, thanks!

**Comment by Konrad-Morawski** [comment]
Done, see if it's acceptable please...

**Comment by pedrovgs** [comment]
Merged ;) Thanks for your help @Karumi/owners !

**Comment by Konrad-Morawski** [comment]
Nice, thank you too for prompt action and for the library, it gives us some spare time for coffee as we'd have to end up writing something similar ourselves otherwise ; )

**Comment by AndyFrench** [comment]
@pedrovgs any idea when this next build is going to be published?

**Comment by pedrovgs** [comment]
@AndyFrench we are going to publish it this week :)

**Comment by xbroak** [comment]
Was this ever published? Seeing: Only one Dexter request at a time is allowed

**Comment by Serchinastico** [comment]
The exception is still there because Dexter won't be able to handle more than one petition at a time, but we introduced a method `isRequestOngoing` that you can call to make sure you won't run into this situation when requesting a permission.

**Comment by xbroak** [comment]
Great, thanks! Missed that!

**Comment by Serchinastico** [comment]
You are welcome :)
